# This is an example configuration file for configuring an OpenOTP daemon.

general:
    name: Core Message Director # To be used in page titles and intra-MD links.
    url: http://123.45.67.89/coremd/ # URL where the web interface may be located. Defaults to:
                                     # http://<web/bind>/
    eventlogger: 127.0.0.1:9090 # The IP:port of the Event Logger to be used when logging global events.
    dc_files: # A list of DC files to be loaded. ORDER IS SENSITIVE!
        - core.dc
        - game.dc
        - minigames.dc

web:
    bind: 0.0.0.0:80 # The webserver should listen on port 80, binding to all interfaces.
    authentication: # HTTP authentication should expect a single username/password, which grants all privileges.
        method: single
        username: foo
        password: bar
    #authentication: # A separate file is used, listing username+password+access level.
    #   method: file
    #   filename: foo.yml

messagedirector:
    bind: 0.0.0.0:6660

roles:
    # This section allows specifying roles that we would like this daemon to perform.
    # For example, let's have a client agent which listens on port 6667 on all interfaces:
    - type: clientagent
      bind: 0.0.0.0:6667

    # Next we'll have a state server, whose control channel is 402000.
    - type: stateserver
      control: 402000

    # Now a database, which listens on channel 402001, generates objects with ids >= 100,000,000+ and
    # uses BerkeleyDB as a backing store.
    - type: database
      control: 402001
      generate:
      # Generate defines the range of DistributedObject ids that the database can create new objects with,
      # and is generally responsible for. Min and max are both optional fields.
        min: 100000000 # Required (no default)
      # max: 200000000 # Default: DOID_T_MAX (UINT_MAX)
      engine:
        type: bdb
        filename: main_database.db

    # We will then create a database state server which provides state-server-like behavior on database
    # objects.  The dbss does not have a control channel, and so cannot generate new objects.
    - type: dbss
      database: 402001 # The channel of the associated database

    # Let's also enable the Event Logger. The Event Logger does not listen on a channel; it uses a
    # separate UDP socket to listen for log events.
    - type: eventlogger
      bind: 0.0.0.0:9090 # REMEMBER: UDP
      output: /var/log/openotp/eventlogger/el-%Y-%m-%d-%H-%M-%S.log # This is a time format.
      rotate_interval: 1d # Rotate the logs daily.

